# Generated by Django 5.1.7 on 2026-06-26

from django.db import migrations, models


def mark_existing_records_submitted(apps, schema_editor):
    apps.get_model("gst_app", "EndOfDay").objects.update(is_submitted=True)


class Migration(migrations.Migration):

    dependencies = [
        ("gst_app", "0013_invoiceattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofday",
            name="delivery_docket_file",
            field=models.FileField(blank=True, upload_to="end-of-day/delivery-dockets/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="endofday",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_records_submitted, migrations.RunPython.noop),
    ]
