# Generated by Django 5.1.15 on 2026-06-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gst_app", "0014_endofday_delivery_docket_and_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="purchase_from",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="invoice",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("supplier_invoice", "Supplier Invoice"),
                    ("cash_purchase", "Cash Purchase"),
                ],
                default="supplier_invoice",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="gst_app.supplier",
            ),
        ),
    ]
